name: Run Laravel Pint

on:
  workflow_dispatch:
  push:
    branches:
      - "*.x"
      - main
      - next
      - next-major
      - beta
      - alpha
      - dev
    paths:
      - "**.php"
      - "!**.blade.php"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Cache dependencies
        uses: ./.github/actions/composer/cache

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Laravel Pint
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix styles using pint with psr-12 rules [skip ci]"
