name: Run Prettier

on:
  workflow_dispatch:
  push:
    branches:
      - "*.x"
      - main
      - next
      - next-major
      - beta
      - alpha
      - dev
    paths:
      - ".devcontainer/**/*.{json,yml}"
      - ".github/**/*.yml"
      - "resources/css/**/*.css"
      - "resources/views/**/*.blade.php"
      - "*.json"
      - "*.yaml"
      - "*.md"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Run code formatting using Prettier
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: fix styles using prettier [skip ci]"
