name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*.x"
      - main
      - next
      - next-major
      - beta
      - alpha
      - dev
  pull_request:
    branches:
      - "*.x"
      - main
      - next
      - next-major
      - beta
      - alpha
      - dev

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        laravel: [9.*, 10.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            canvas: ^8.1.3
            testbench: ^8.5.2
            testbench-dusk: ^8.6.1
            php: 8.1
          - laravel: 9.*
            canvas: ^7.5.0
            testbench: ^7.24.1
            testbench-dusk: ^7.25.1
            php: 8.0

    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require --dev  "orchestra/canvas:${{ matrix.canvas }}" "orchestra/testbench:${{ matrix.testbench }}" "orchestra/testbench-dusk:${{ matrix.testbench-dusk }}" --no-interaction --no-update
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List installed dependencies
        run: composer show -D

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up testing
        run: |
          ./vendor/orchestra/testbench-core/create-sqlite-db
          ./vendor/orchestra/testbench-dusk/create-sqlite-db
          ./vendor/bin/dusk-updater detect --auto-update
          npm run build
          npx soketi start &
          npx wait-on tcp:127.0.0.1:6001

      - name: Execute tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          timeout_seconds: 600
          retry_on: error
          retry_wait_seconds: 5
          command: composer test -- --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload browser screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: browser screenshots
          path: tests/Browser/screenshots

      - name: Upload browser console logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: browser console
          path: tests/Browser/console

      - name: Upload testbench core logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: testbench core
          path: vendor/orchestra/testbench-core/laravel/storage/logs/

      - name: Upload testbench dusk logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: testbench dusk
          path: vendor/orchestra/testbench-dusk/laravel/storage/logs/
